# Generated by Django 5.0.4 on 2024-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_satus_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
